/**
 * アプリケーションクライアントイベントファクトリー
 * クライアントサイドで発生したイベントを生成する
 * クライアントサイドからapiを通じて生成される想定
 * @namespace clientEvent
 */

import { IExtendId } from './autoGenerated';

export interface IAttributes {
    client: string;
    occurredAt: Date;
    url: string;
    label: string;
    category: string;
    action: string;
    message: string;
    notes: string;
    useragent: string;
    location: number[];
    transaction?: string;
}

export type IClientEvent = IExtendId<IAttributes>;
